databases:
  - name: task-management-app-db
    plan: free
    region: oregon

services:
  - type: web
    name: my-spring-boot-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: task-management-app-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: task-management-app-db
          property: username
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: task-management-app-db
          property: password
      - key: AWS_ACCESS_KEY
        value: ${AWS_ACCESS_KEY}
      - key: AWS_SECRET_KEY
        value: ${AWS_SECRET_KEY}
      - key: AWS_ENDPOINT
        value: ${AWS_ENDPOINT}
      - key: MAIL_HOSTNAME
        value: ${MAIL_HOSTNAME}
      - key: MAIL_PASSWORD
        value: ${MAIL_PASSWORD}
