services:
  - type: web
    name: my-spring-boot-app
    env: java
    plan: free
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/security-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: my-postgres-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: my-postgres-db
          property: username
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: my-postgres-db
          property: password
databases:
  - name: my-postgres-db
    plan: free
    region: oregon
